import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity()
export class User {
  // The PrimaryGeneratedColumn decorator is used to indicate that the id field is a primary key and its value will be automatically generated by the database. This means that when a new user is created, the database will automatically assign a unique value to the id field,
  // ensuring that each user has a distinct identifier.
  @PrimaryGeneratedColumn()
  id: number;

  @Column({
    type: 'varchar',
    length: 96,
    nullable: false,
  })
  name: string;

  @Column({
    type: 'varchar',
    length: 96,
    nullable: false,
    unique: true,
  })
  email: string;

  @Column({
    type: 'varchar',
    length: 96,
    nullable: false,
  })
  password: string;
}
